In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [3]:
from google.colab import files
uploaded = files.upload()

Saving practiceDataset.csv to practiceDataset.csv

In [4]:
data = pd.read_csv('/content/practiceDataset.csv')
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
data.shape

(1460, 81)

In [6]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [7]:
data['LotFrontage'] = data['LotFrontage'].fillna(data['LotFrontage'].mean())

In [8]:
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [9]:
X = data[['MSSubClass','MSZoning','LotFrontage','LotArea','HouseStyle','OverallQual','OverallCond']]
X

,MSSubClass,MSZoning,LotFrontage,LotArea,HouseStyle,OverallQual,OverallCond
0,60,RL,65.0,8450,2Story,7,5
1,20,RL,80.0,9600,1Story,6,8
2,60,RL,68.0,11250,2Story,7,5
3,70,RL,60.0,9550,2Story,7,5
4,60,RL,84.0,14260,2Story,8,5
...,...,...,...,...,...,...,...
1455,60,RL,62.0,7917,2Story,6,5
1456,20,RL,85.0,13175,1Story,6,6
1457,70,RL,66.0,9042,2Story,7,9
1458,20,RL,68.0,9717,1Story,5,6
1459,20,RL,75.0,9937,1Story,5,6

In [10]:
Y = data['SalePrice']
Y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
le_MSZoning = LabelEncoder()
le_HouseStyle = LabelEncoder()

In [12]:
X['MSZoning'] = le_MSZoning.fit_transform(X['MSZoning'])
X['HouseStyle'] = le_MSZoning.fit_transform(X['HouseStyle'])

In [13]:
X.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,HouseStyle,OverallQual,OverallCond
0,60,3,65.0,8450,5,7,5
1,20,3,80.0,9600,2,6,8
2,60,3,68.0,11250,5,7,5
3,70,3,60.0,9550,5,7,5
4,60,3,84.0,14260,5,8,5

In [14]:
model = LinearRegression()
model.fit(X.values,Y)

LinearRegression()

In [15]:
price = [[55,2,77.0,8000,4,8,5]]
result = model.predict(price)
print(result)

[266762.19274741]

In [16]:
print('The price of the House is {0} Rupees'.format(result))

The price of the House is [266762.19274741] Rupees